workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: ad_hoc # or ad_hoc for testing
        bundle_identifier: com.Bennie.burnbank
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          cd ios
          flutter build ios --release --no-codesign
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - bmccoy67@gmail.com # Replace with your email