name: burnbank
description: "Step-based reward tracker with Firebase and Apple Health support."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # Authentication
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^7.0.1

  # State Management
  provider: ^6.0.5
  shared_preferences: ^2.2.0

  # Mapping
  flutter_map: ^6.1.0
  geolocator: ^10.1.0

  # UI & Charts
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  cached_network_image: ^3.2.3

  # Utility & Platform Integration
  intl: ^0.20.2 # Downgraded for health plugin compatibility
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.0
  uuid: ^4.5.1
  url_launcher: ^6.1.12

  # Monetization & Health Integration
  # google_mobile_ads: ^3.0.0 # Uncomment when you're ready to use ads
  in_app_purchase: ^3.1.7
  health: ^12.1.0 # Stable version with iOS 14+ support
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

scripts:
  pre-build:
    - flutter clean
    - flutter pub get
    - flutter precache --ios

