name: burnbank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5

  # Authentication
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0

  # State management
  provider: ^6.0.5
  shared_preferences: ^2.2.0

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0
  cached_network_image: ^3.2.3

  # Utilities
  intl: ^0.18.1
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^4.0.2
  path_provider: ^2.1.0
  uuid: ^3.0.7
  url_launcher: ^6.1.12

  # Ads / Monetization / Health
  # Uncomment when ready:
  # google_mobile_ads: ^3.0.0
  in_app_purchase: ^3.1.7
  health: ^12.1.0
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
